### ISSUE TITLE
Show the source description somewhere

### ISSUE THREAD

**Issue by alecgorge** [RelistenNet/relisten-web#11]
Sometimes you need the show description for the setlist: http://relisten.live/dead-and-co/2017/05/28

**Comment by switz** [comment]
The description is HTML? I can't render user input unsanitized.

**Comment by alecgorge** [comment]
I don't think it is HTML? If it is, archive.org doesn't render it as HTML. It is generally just preformatted text

**Comment by switz** [comment]
https://relistenapi.alecgorge.com/api/v2/artists/dead-and-co/years/2017/2017-05-28

```"<div>Set 1</div><div>01  Feel Like a Stranger</div><div>02  Bertha</div><div>03  New Minglewood Blues</div><div>04  Cassidy</div><div>05  Peggy-O</div><div>06  Loose Lucy</div><div>07  Sugaree</div><div>08  Samson & Delilah</div><div><br /></div><div>Set 2</div><div>09  Lost Sailor ></div><div>10  Saint of Circumstance</div><div>11  Crazy Fingers</div><div>12  Scarlet Begonias ></div><div>13  Fire On The Mountain ></div><div>14  Drums ></div><div>15  Space ></div><div>16  Dear Prudence</div><div>17  Casey Jones</div><div>Encore</div><div>18  Touch Of Grey</div>"
```

**Comment by alecgorge** [comment]
Oh shoot. I looked into what I was doing because I didn't remember rendering HTML and I was using NSAttributedString's NSHTMLTextDocumentType feature.

What about something like [react-safe-html](https://github.com/brigand/react-safe-html)?

**Comment by switz** [comment]
@alecgorge any chance we can do something that doesn't involve raw HTML? I _could_ use react-safe-html, but would prefer not to if possible. Maybe html -> markdown?
