### ISSUE TITLE
Use a proxy for phish.in to avoid getting the track blocked for not loading over HTTPS

### ISSUE THREAD

**Issue by alecgorge** [RelistenNet/relisten-web#15]
Phish.in doesn't support HTTPS. Fortunately my transparent caching proxy does:

`http://phish.in/audio/000/015/550/15550.mp3`

-->

`https://phishin_api.alecgorge.com/audio/000/015/550/15550.mp3`

It caches MP3s very aggressively and serves them up very fast. PhishOD uses this right now so most popular things are hot in the cache and the hit rate is pretty high.

**Comment by switz** [comment]
Should we just store the cache URL in the db to return from the API?

**Comment by alecgorge** [comment]
I've gone back and forth on this but I think it is really more of a client specific thing. I have a kill switch in the PhishOD app config that is loaded on app open that turns off the rewriting in case my proxy server is having issues.

I don't know though, I can make an argument for both.

**Comment by switz** [comment]
I think it supports https now
