### ISSUE TITLE
Add a smart app banner for Relisten

### ISSUE THREAD

**Issue by farktronix** [RelistenNet/relisten-web#34]
It'd be great if relisten.net had a [smart app banner](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html) linking to the iOS app.

From what I've read, having this banner is also one of the only ways to fix up universal links for an app.

It should be as simple as adding this tag to the header: 
`<meta name="apple-itunes-app" content="add-id=715886886">`

If you want to get extra fancy, you can add `app-argument=https://relisten.live/...` to that tag and update it based on the currently viewed/playing show. That would let the user jump right to the current show in the app by tapping on the banner.

**Comment by switz** [comment]
Fixed in https://github.com/RelistenNet/relisten-web/commit/674f7d3d1ca0ba2ca1d064b9371e6c0a224bc391

Should the app-argument be dynamic based on the active URL or stick with the server-rendered URL? It does the latter for now.
