### ISSUE TITLE
Use the same icon as the app for the favicon

### ISSUE THREAD

**Issue by farktronix** [RelistenNet/relisten-web#36]
The favicon for relisten.live is an "L" that's just a single size:
![favicon](https://user-images.githubusercontent.com/4943/45376937-fdfd3680-b5ad-11e8-99a8-7f0aab8a9028.png)

It looks like there are lots of different favicon sizes supported now. Could we replace it with these? (thanks to [favicon-generator.org](https://www.favicon-generator.org) 

![app icon-small](https://user-images.githubusercontent.com/4943/45377290-05710f80-b5af-11e8-897f-5ae4a99b7e1e.png)

[Relisten-favicons.zip](https://github.com/RelistenNet/relisten-web/files/2372075/Relisten-favicons.zip)

``` 
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#009dc0">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#009dc0">
```

**Comment by switz** [comment]
The favicon is a nod back to the old Listen to the Dead days. It’s the same favicon.

I’m open to switching it, but enjoy the nostalgia a bit.

**Comment by Thenlie** [comment]
The current favicon is not visible at all on darkmode browsers. IMO, this suggestion is the better solution, but a white "L" could also be added for dark browsers. 

I am happy to make a PR for this if you let me know which option is preferred!

**Comment by switz** [comment]
I think I'm over the nostalgia, let's aim for consistency. If you want to send a PR with the modern relisten logo I'm happy to merge it.

**Comment by Thenlie** [comment]
> I think I'm over the nostalgia, let's aim for consistency. If you want to send a PR with the modern relisten logo I'm happy to merge it.

PR created, don't hesitate to reach out if you have any questions or concerns. 
- #62

**Comment by switz** [comment]
I left some code comments on the PR

**Comment by Thenlie** [comment]
> I left some code comments on the PR

Appreciate it! I don't know if I am just blind, but I am not seeing any comments at the moment.

**Comment by switz** [comment]
Sorry I forgot to hit “start review”Sent from my phoneOn Jul 3, 2023, at 11:11 AM, Leithen ***@***.***> wrote:﻿

I left some code comments on the PR

Appreciate it! I don't know if I am just blind, but I am not seeing any comments at the moment.
