### ISSUE TITLE
Weird Chrome 74 behavior: tracks skip playing

### ISSUE THREAD

**Issue by colinhowells** [RelistenNet/relisten-web#49]
Something I've noticed on Chrome 74, which I hadn't experienced previously: tracks suddenly stop playing a few minutes in, and immediately begin playing the next track.

My first thought was that Chrome was detecting the preloading of the next track and interpreting that as an instruction to play it once successfully loaded, but that doesn't seem to be the case, and I'm not sure what causes Chrome to bail on the current track.

I'll keep digging for more information for you and report back here, but I thought I'd pass this along in case anyone else'd noticed it as well in the meantime.

(I should mention for clarity this is not something I see on iOS or non-Chrome on macOS.)

**Comment by switz** [comment]
Someone else actually reported this today. So it's not just you. This was happening on some browsers when the track (that you're currently on) finishes loading, because at that point we switch to web audio on the fly to handle gapless playback.

Next time it happens, can you paste your developer console here? You should see something like:

```8:switch to web audio 31.35464 false 485.485714 485.4533333333333 0.03238066666665418 {playbackType: "HTML5", webAudioLoadingState: "LOADED"}```

I would wager one of those numbers is returning `NaN`.

**Comment by colinhowells** [comment]
Hm, I'm not getting bad timecodes, but I am getting `preload undefined`

```js
_app.js:1 21:pause {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}
_app.js:1 22:preload undefined {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}playbackType: "WEBAUDIO"webAudioLoadingState: "LOADED"__proto__: Object
_app.js:1 21:pause {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}
_app.js:1 19:onEnded {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}
_app.js:1 21:pause {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}playbackType: "WEBAUDIO"webAudioLoadingState: "LOADED"__proto__: Object
_app.js:1 21:pause {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}playbackType: "WEBAUDIO"webAudioLoadingState: "LOADED"__proto__: Object
_app.js:1 22:pause {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}playbackType: "WEBAUDIO"webAudioLoadingState: "LOADED"__proto__: Object
_app.js:1 22:pause {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}playbackType: "WEBAUDIO"webAudioLoadingState: "LOADED"__proto__: Object
_app.js:1 22:play {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}playbackType: "WEBAUDIO"webAudioLoadingState: "LOADED"__proto__: Object
_app.js:1 22:pause {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}playbackType: "WEBAUDIO"webAudioLoadingState: "LOADED"__proto__: Object
_app.js:1 23:preload undefined {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}playbackType: "WEBAUDIO"webAudioLoadingState: "LOADED"__proto__: Object
_app.js:1 22:pause {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}
```

**Comment by switz** [comment]
Hmm it just happened to me.

```
_app.js:1 15:switch to web audio 0 true NaN 253.50666666666666 NaN Object```

`this.audio.duration => NaN` https://github.com/RelistenNet/relisten-web/blob/master/static/gapless.js#L290

I just got to Jazzfest today so I'm not sure when I'll have time to look into it, but for the time being I'll disable gapless playback which will bypass the bug. Odd.

**Comment by colinhowells** [comment]
Ha, I got one:

```js
_app.js:1 21:onEnded {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}
_app.js:1 20:pause {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}
_app.js:1 21:pause {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}
_app.js:1 21:pause {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}
_app.js:1 21:play {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}
_app.js:1 21:pause {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}
_app.js:1 22:preload undefined {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}
```

That's the entirety of one track sticking and it moving immediately to the next one.

**Comment by switz** [comment]
> By the way I'm never seeing switch to web audio - do I have gapless disabled and not know it?

Web audio was only disabled (before my last commit) on Firefox and mobile. Firefox has had this bug forever and I couldn't figure out why. https://github.com/RelistenNet/relisten-web/blob/master/lib/player.js#L124

Maybe if your browser's useragent has firefox in it? Or if it "thinks" you're on mobile?

**Comment by colinhowells** [comment]
I have new, exotic errors!

```js
_app.js:1 27:play {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}
_app.js:1 27:pause {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}
_app.js:1 26:onEnded {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}
_app.js:1 27:pause {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}
commons.8e1b91cacb7ed6f2e427.js:23 Uncaught TypeError: Cannot read property 'idx' of undefined
    at Object.onStartNewTrack (commons.8e1b91cacb7ed6f2e427.js:23)
    at e.value (commons.8e1b91cacb7ed6f2e427.js:23)
    at e.value (commons.8e1b91cacb7ed6f2e427.js:23)
onStartNewTrack @ commons.8e1b91cacb7ed6f2e427.js:23
value @ commons.8e1b91cacb7ed6f2e427.js:23
value @ commons.8e1b91cacb7ed6f2e427.js:23
_app.js:1 24:onEnded {playbackType: "WEBAUDIO", webAudioLoadingState: "LOADED"}
commons.8e1b91cacb7ed6f2e427.js:23 Uncaught TypeError: Cannot read property 'idx' of undefined
    at Object.onStartNewTrack (commons.8e1b91cacb7ed6f2e427.js:23)
    at e.value (commons.8e1b91cacb7ed6f2e427.js:23)
    at e.value (commons.8e1b91cacb7ed6f2e427.js:23)
```

**Comment by switz** [comment]
Weird, weird, weird. Can you try hard refreshing? Shift+ctrl+r (or shift + click refresh).
It shouldn't try to load Webaudio anymore at all

**Comment by colinhowells** [comment]
`player.state.webAudioIsDisabled` is false for me.

**Comment by switz** [comment]
I think I was able to track down and fix this bug so I'm re-enabling gapless audio for everyone (except mobile and firefox users, which seem to still have some issues). As always, we'll do things live here. It certainly may not be fixed, but we'll find out sooner if I just kick it back on and see what happens. Bear with me.

Cheers.
