### ISSUE TITLE
Redesign player

### ISSUE THREAD

**Issue by switz** [RelistenNet/relisten-web#5]

**Comment by tbolt** [comment]
ill take this

**Comment by switz** [comment]
This is largely done it just needs to be a bit friendlier across screen sizes.

**Comment by switz** [comment]
I'm absolutely open to rethinking the whole player if you think it can be improved though.

**Comment by tbolt** [comment]
ok, no problem. is there any design work you need help on?

**Comment by switz** [comment]
Yeah, we'll need some pages for Today in History (see: http://relisten.net/today) and Live (see: http://relisten.net/live). Any ideas there?

**Comment by switz** [comment]
Also I somewhat hate the current navigation/menu -- would love some help with that.

**Comment by tbolt** [comment]
Wanted to throw this idea out there as it would take some slight tweaking to the site structure. This might be a bit aggressive so totally cool if you want to keep it closer to the current style. 

My thinking was to have the first view be a collection of the artists with a "search" that really just filters them live. [Like this.](https://codepen.io/robooneus/pen/ivdFH). We could source artist photos from last.fm's API. Not sure if that violates any terms or anything. Once an artist was selected the page would update with the list of years, shows, songs, etc... Pretty much how it is now. I think moving this way we could start making the site responsive as well. The player would always be fixed but floating at the bottom when active.

![relisten_idea1](https://user-images.githubusercontent.com/2279260/30253952-b524ee96-965d-11e7-82da-52a9a256eac6.png)

**Comment by tbolt** [comment]
Any thoughts on this @switz?

**Comment by switz** [comment]
Thanks for putting that together, but I'm not currently interested in doing such a fundamental redesign. We'll probably add a search bar in the header since the API supports strong search.

**Comment by tbolt** [comment]
No problem, ill stick with some minor updates to the items you mentioned.
