### ISSUE TITLE
Web frontend showing incorrect venue for shows

### ISSUE THREAD

**Issue by lilbud** [RelistenNet/relisten-web#60]
I was going through Relisten looking through shows and I noticed that all the Grateful Dead shows listed for the Capitol Theater are only showing for the one in Port Chester, even if the show wasn't played there. While the Dead did play the one in Port Chester, NY a number of times, it was only up until 1971-02-24. After that the only one they played was the one in Passaic, NJ. 

The venue shows correct on Archive.org, which makes me think it's an issue with the frontend maybe mixing up the two due to identical names. I cross checked both Jerry Garcia's and the official Grateful Dead website, and this too confirms they only played the Port Chester one until 1971 and didn't play there again.

**Comment by switz** [comment]
This is a https://github.com/RelistenNet/RelistenApi/issues/45 issue, not related to the website itself so I'm going to close this issue.
