### ISSUE TITLE
Web UI outputting raw Tailwind

### ISSUE THREAD

**Issue by jbwharris** [RelistenNet/relisten-web#69]
There was just [a bug posted](https://github.com/web-scrobbler/web-scrobbler/issues/4048) on @web-scrobbler about the plugin no longer working on the site. I took a look at the code and noticed it was mostly just a mess of Tailwind classes with nothing really labelled.

![image](https://github.com/RelistenNet/relisten-web/assets/2962327/b4f65e17-a0c6-45d4-9186-0dddb69dd9c8)

I took a look in the Wayback Machine and saw that it was previously structured, so I wasn't sure if there was rebuild going on, or something messed up compiling the site that might have caused this issue. 
![image](https://github.com/RelistenNet/relisten-web/assets/2962327/07bc8d1b-2f9f-4c40-97f9-930c8dfed3ff)

I didn't want to rush off and fix the Web Scrobbler connector, only to find it might have just been code regression of some sort. Web Scrobbler just needs consistent class names to target to make the connectors work.

**Comment by switz** [comment]
Yeah, we upgraded our website and no longer use className like that. I'm more than happy to add some classNames back in specifically for you, seems like a cool project!

Can you tell me specifically what data you would need access to? Seems like:

* is playing/paused
* band name
* song name
* "album" name

anything else? maybe we'll just expose those as `data-` attributes for you.

**Comment by jbwharris** [comment]
@switz I just made a PR for where the classes would need to be added. If you wanted to use `data-` attributes, that could work too. We'd just need to update the existing connector, but that's no biggie if you wanted to go that route.
